#!/usr/bin/env python3
"""Tests for make-canaries.py covering the 2026-04-24 P0 patches.

Runs with stdlib unittest; no external deps. From the repo root:

    python3 defense-beacon/reference/tests/make_canaries_test.py
"""
from __future__ import annotations

import importlib.util
import os
import re
import sys
import tempfile
import textwrap
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
MODULE_PATH = HERE.parent / "make-canaries.py"


def _load_module():
    """Import make-canaries.py by path — filename has a hyphen, so the usual
    import syntax does not work."""
    spec = importlib.util.spec_from_file_location("make_canaries", MODULE_PATH)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


mc = _load_module()


class SurfaceIdValidationTest(unittest.TestCase):
    """P3 — surface-id must reject path traversal, newlines, and anything that
    could escape OUT_DIR or inject registry lines."""

    def test_accepts_valid_ids(self):
        for sid in ["ab", "cms-workspace-root", "a1", "agent-project-alpha",
                    "a" + "b" * 62 + "c"]:  # 64 chars
            mc._validate_surface_id(sid, "test")

    def test_rejects_path_traversal(self):
        for bad in ["../../../tmp/pwn", "../etc/passwd", "a/b", "a\\b"]:
            with self.subTest(bad=bad), self.assertRaises(SystemExit):
                mc._validate_surface_id(bad, "test")

    def test_rejects_newlines_and_nuls(self):
        for bad in ["a\nb", "a\rb", "a\x00b", "a\tb"]:
            with self.subTest(bad=bad), self.assertRaises(SystemExit):
                mc._validate_surface_id(bad, "test")

    def test_rejects_boundary_dashes(self):
        for bad in ["-leading", "trailing-", "-", "--"]:
            with self.subTest(bad=bad), self.assertRaises(SystemExit):
                mc._validate_surface_id(bad, "test")

    def test_rejects_uppercase_and_punct(self):
        for bad in ["MixedCase", "has_underscore", "has.dot", "has space",
                    "has/slash", "has$sig"]:
            with self.subTest(bad=bad), self.assertRaises(SystemExit):
                mc._validate_surface_id(bad, "test")

    def test_rejects_length_boundaries(self):
        # 1-char fails (grammar requires first AND last alnum, min 2)
        with self.assertRaises(SystemExit):
            mc._validate_surface_id("a", "test")
        # 65-char fails
        with self.assertRaises(SystemExit):
            mc._validate_surface_id("a" + "b" * 63 + "c", "test")


class RegistryMarkerCollisionTest(unittest.TestCase):
    """P2 — the managed-block strip regex must anchor to line boundaries.
    Old non-multiline `.*?` would match from a user comment quoting the
    marker and delete everything up to the first end-marker."""

    def _build_existing_registry(self) -> str:
        # Realistic hostile case: a user comment quotes the begin-marker as
        # documentation on its own line (e.g. a README-style note). Old
        # unanchored `.*?` regex anchors at that spurious occurrence and
        # deletes every line between it and the real end-marker, including
        # user-authored canary lines. The fixed regex uses `^` + MULTILINE
        # so the marker only matches at the start of a line without leading
        # comment punctuation.
        return textwrap.dedent(f"""\
            # user-authored canaries
            # note: the managed block below starts at the line
            #   {mc.REGISTRY_MARK_BEGIN}
            # and ends at the matching end-marker.
            user-canary-one
            user-canary-two
            {mc.REGISTRY_MARK_BEGIN}
            # Generated by defense-beacon/reference/make-canaries.py
            old-managed-line-1
            old-managed-line-2
            {mc.REGISTRY_MARK_END}
            # trailing user comment
            """)

    def test_regex_preserves_user_lines(self):
        """The current regex must match only the real managed block, not
        span from the quoted marker in the user comment."""
        existing = self._build_existing_registry()
        pattern = re.compile(
            r"^" + re.escape(mc.REGISTRY_MARK_BEGIN) + r"[^\n]*\n"
            r".*?"
            r"^" + re.escape(mc.REGISTRY_MARK_END) + r"[^\n]*\n?",
            re.DOTALL | re.MULTILINE,
        )
        cleaned = pattern.sub("", existing)
        self.assertIn("user-canary-one", cleaned)
        self.assertIn("user-canary-two", cleaned)
        self.assertIn("# note: the managed block below", cleaned)
        self.assertIn("# trailing user comment", cleaned)
        self.assertNotIn("old-managed-line-1", cleaned)
        self.assertNotIn("old-managed-line-2", cleaned)

    def test_old_unanchored_regex_would_have_failed(self):
        """Proof that the old non-multiline form deleted user content —
        kept as a regression witness so the collision mode stays
        demonstrable if someone refactors the regex."""
        existing = self._build_existing_registry()
        bad_pattern = re.compile(
            re.escape(mc.REGISTRY_MARK_BEGIN) + r".*?" + re.escape(mc.REGISTRY_MARK_END) + r"\n?",
            re.DOTALL,
        )
        broken = bad_pattern.sub("", existing)
        # The old regex anchored to the quoted marker in the user comment
        # and ate the user-authored canary lines between there and the
        # real end-marker. This is the bug the current fix prevents.
        self.assertNotIn("user-canary-one", broken)
        self.assertNotIn("user-canary-two", broken)


class AtomicWriteTest(unittest.TestCase):
    """P5 — _atomic_write_text must not leave a partial file on error, and
    must replace the target in one syscall."""

    def test_atomic_write_replaces_target(self):
        with tempfile.TemporaryDirectory() as d:
            target = Path(d) / "state.json"
            target.write_text("old-content")
            mc._atomic_write_text(target, "new-content")
            self.assertEqual(target.read_text(), "new-content")

    def test_atomic_write_no_temp_leftover(self):
        with tempfile.TemporaryDirectory() as d:
            target = Path(d) / "state.json"
            mc._atomic_write_text(target, "content")
            leftovers = [p for p in Path(d).iterdir() if p.name != "state.json"]
            self.assertEqual(leftovers, [], f"leftover tempfiles: {leftovers}")


class PathTraversalGuardTest(unittest.TestCase):
    """P3 — emit_beacon must refuse to write outside OUT_DIR even if a caller
    bypasses the surface-id grammar check."""

    def test_valid_id_writes_inside_out_dir(self):
        with tempfile.TemporaryDirectory() as d:
            d_path = Path(d)
            tpl = d_path / "tpl.md"
            tpl.write_text("id={{SURFACE_ID}} t1={{CANARY_TOKEN_1}} t2={{CANARY_TOKEN_2}} at={{ISSUED_UTC}}")
            out = d_path / "out"
            orig_tpl = mc.BEACON_TEMPLATE
            orig_out = mc.OUT_DIR
            try:
                mc.BEACON_TEMPLATE = tpl
                mc.OUT_DIR = out
                p = mc.emit_beacon("valid-id", "shaped", "phrase", "now")
                self.assertTrue(p.exists())
                self.assertEqual(p.parent.resolve(), out.resolve())
            finally:
                mc.BEACON_TEMPLATE = orig_tpl
                mc.OUT_DIR = orig_out

    def test_invalid_id_rejected(self):
        with tempfile.TemporaryDirectory() as d:
            d_path = Path(d)
            tpl = d_path / "tpl.md"
            tpl.write_text("x")
            out = d_path / "out"
            orig_tpl = mc.BEACON_TEMPLATE
            orig_out = mc.OUT_DIR
            try:
                mc.BEACON_TEMPLATE = tpl
                mc.OUT_DIR = out
                with self.assertRaises(SystemExit):
                    mc.emit_beacon("../../../tmp/pwn", "s", "p", "t")
            finally:
                mc.BEACON_TEMPLATE = orig_tpl
                mc.OUT_DIR = orig_out


if __name__ == "__main__":
    unittest.main(verbosity=2)
