#!/usr/bin/env python3
"""Tests for make-canaries.py covering the 2026-04-24 P0 patches.

Runs with stdlib unittest; no external deps. From the repo root:

    python3 defense-beacon/reference/tests/make_canaries_test.py
"""
from __future__ import annotations

import importlib.util
import json
import os
import re
import subprocess
import sys
import tempfile
import textwrap
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
MODULE_PATH = HERE.parent / "make-canaries.py"


def _load_module():
    """Import make-canaries.py by path — filename has a hyphen, so the usual
    import syntax does not work."""
    spec = importlib.util.spec_from_file_location("make_canaries", MODULE_PATH)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


mc = _load_module()


class SurfaceIdValidationTest(unittest.TestCase):
    """P3 — surface-id must reject path traversal, newlines, and anything that
    could escape OUT_DIR or inject registry lines."""

    def test_accepts_valid_ids(self):
        for sid in ["ab", "cms-workspace-root", "a1", "agent-project-alpha",
                    "a" + "b" * 62 + "c"]:  # 64 chars
            mc._validate_surface_id(sid, "test")

    def test_rejects_path_traversal(self):
        for bad in ["../../../tmp/pwn", "../etc/passwd", "a/b", "a\\b"]:
            with self.subTest(bad=bad), self.assertRaises(SystemExit):
                mc._validate_surface_id(bad, "test")

    def test_rejects_newlines_and_nuls(self):
        for bad in ["a\nb", "a\rb", "a\x00b", "a\tb"]:
            with self.subTest(bad=bad), self.assertRaises(SystemExit):
                mc._validate_surface_id(bad, "test")

    def test_rejects_boundary_dashes(self):
        for bad in ["-leading", "trailing-", "-", "--"]:
            with self.subTest(bad=bad), self.assertRaises(SystemExit):
                mc._validate_surface_id(bad, "test")

    def test_rejects_uppercase_and_punct(self):
        for bad in ["MixedCase", "has_underscore", "has.dot", "has space",
                    "has/slash", "has$sig"]:
            with self.subTest(bad=bad), self.assertRaises(SystemExit):
                mc._validate_surface_id(bad, "test")

    def test_rejects_length_boundaries(self):
        # 1-char fails (grammar requires first AND last alnum, min 2)
        with self.assertRaises(SystemExit):
            mc._validate_surface_id("a", "test")
        # 65-char fails
        with self.assertRaises(SystemExit):
            mc._validate_surface_id("a" + "b" * 63 + "c", "test")


class RegistryMarkerCollisionTest(unittest.TestCase):
    """P2 — the managed-block strip regex must anchor to line boundaries.
    Old non-multiline `.*?` would match from a user comment quoting the
    marker and delete everything up to the first end-marker."""

    def _build_existing_registry(self) -> str:
        # Realistic hostile case: a user comment quotes the begin-marker as
        # documentation on its own line (e.g. a README-style note). Old
        # unanchored `.*?` regex anchors at that spurious occurrence and
        # deletes every line between it and the real end-marker, including
        # user-authored canary lines. The fixed regex uses `^` + MULTILINE
        # so the marker only matches at the start of a line without leading
        # comment punctuation.
        return textwrap.dedent(f"""\
            # user-authored canaries
            # note: the managed block below starts at the line
            #   {mc.REGISTRY_MARK_BEGIN}
            # and ends at the matching end-marker.
            user-canary-one
            user-canary-two
            {mc.REGISTRY_MARK_BEGIN}
            # Generated by defense-beacon/reference/make-canaries.py
            old-managed-line-1
            old-managed-line-2
            {mc.REGISTRY_MARK_END}
            # trailing user comment
            """)

    def test_regex_preserves_user_lines(self):
        """The current regex must match only the real managed block, not
        span from the quoted marker in the user comment."""
        existing = self._build_existing_registry()
        pattern = re.compile(
            r"^" + re.escape(mc.REGISTRY_MARK_BEGIN) + r"[^\n]*\n"
            r".*?"
            r"^" + re.escape(mc.REGISTRY_MARK_END) + r"[^\n]*\n?",
            re.DOTALL | re.MULTILINE,
        )
        cleaned = pattern.sub("", existing)
        self.assertIn("user-canary-one", cleaned)
        self.assertIn("user-canary-two", cleaned)
        self.assertIn("# note: the managed block below", cleaned)
        self.assertIn("# trailing user comment", cleaned)
        self.assertNotIn("old-managed-line-1", cleaned)
        self.assertNotIn("old-managed-line-2", cleaned)

    def test_old_unanchored_regex_would_have_failed(self):
        """Proof that the old non-multiline form deleted user content —
        kept as a regression witness so the collision mode stays
        demonstrable if someone refactors the regex."""
        existing = self._build_existing_registry()
        bad_pattern = re.compile(
            re.escape(mc.REGISTRY_MARK_BEGIN) + r".*?" + re.escape(mc.REGISTRY_MARK_END) + r"\n?",
            re.DOTALL,
        )
        broken = bad_pattern.sub("", existing)
        # The old regex anchored to the quoted marker in the user comment
        # and ate the user-authored canary lines between there and the
        # real end-marker. This is the bug the current fix prevents.
        self.assertNotIn("user-canary-one", broken)
        self.assertNotIn("user-canary-two", broken)


class AtomicWriteTest(unittest.TestCase):
    """P5 — _atomic_write_text must not leave a partial file on error, and
    must replace the target in one syscall."""

    def test_atomic_write_replaces_target(self):
        with tempfile.TemporaryDirectory() as d:
            target = Path(d) / "state.json"
            target.write_text("old-content")
            mc._atomic_write_text(target, "new-content")
            self.assertEqual(target.read_text(), "new-content")

    def test_atomic_write_no_temp_leftover(self):
        with tempfile.TemporaryDirectory() as d:
            target = Path(d) / "state.json"
            mc._atomic_write_text(target, "content")
            leftovers = [p for p in Path(d).iterdir() if p.name != "state.json"]
            self.assertEqual(leftovers, [], f"leftover tempfiles: {leftovers}")


class PathTraversalGuardTest(unittest.TestCase):
    """P3 — emit_beacon must refuse to write outside OUT_DIR even if a caller
    bypasses the surface-id grammar check."""

    def test_valid_id_writes_inside_out_dir(self):
        with tempfile.TemporaryDirectory() as d:
            d_path = Path(d)
            tpl = d_path / "tpl.md"
            tpl.write_text("id={{SURFACE_ID}} t1={{CANARY_TOKEN_1}} t2={{CANARY_TOKEN_2}} at={{ISSUED_UTC}}")
            out = d_path / "out"
            orig_tpl = mc.BEACON_TEMPLATE
            orig_out = mc.OUT_DIR
            try:
                mc.BEACON_TEMPLATE = tpl
                mc.OUT_DIR = out
                p = mc.emit_beacon("valid-id", "shaped", "phrase", "now")
                self.assertTrue(p.exists())
                self.assertEqual(p.parent.resolve(), out.resolve())
            finally:
                mc.BEACON_TEMPLATE = orig_tpl
                mc.OUT_DIR = orig_out

    def test_invalid_id_rejected(self):
        with tempfile.TemporaryDirectory() as d:
            d_path = Path(d)
            tpl = d_path / "tpl.md"
            tpl.write_text("x")
            out = d_path / "out"
            orig_tpl = mc.BEACON_TEMPLATE
            orig_out = mc.OUT_DIR
            try:
                mc.BEACON_TEMPLATE = tpl
                mc.OUT_DIR = out
                with self.assertRaises(SystemExit):
                    mc.emit_beacon("../../../tmp/pwn", "s", "p", "t")
            finally:
                mc.BEACON_TEMPLATE = orig_tpl
                mc.OUT_DIR = orig_out


class ConcurrencyLockTest(unittest.TestCase):
    """P5 — concurrent invocations must not corrupt state. The fcntl.flock
    LOCK_EX|LOCK_NB acquired in _acquire_lock serializes the state
    read-modify-write sequence. Second process gets BlockingIOError,
    prints a clear error, and exits non-zero — no silent last-writer-wins."""

    def test_second_invocation_rejected_while_first_holds_lock(self):
        """Open a lock by hand, then run make-canaries.py as a subprocess
        against the same state file. The subprocess must fail fast with
        exit code 2 and a message naming the lock file — not clobber state."""
        import fcntl

        with tempfile.TemporaryDirectory() as d:
            d_path = Path(d)
            # Isolate state/out/registry/template so the test does not touch
            # the real repo layout. make-canaries resolves these from the
            # script location, so we drive it via a wrapper that points to
            # a scratch dir.
            scratch_repo = d_path / "reference"
            scratch_repo.mkdir()
            template = scratch_repo / "beacon-template-v1.md"
            template.write_text(
                "id={{SURFACE_ID}} t1={{CANARY_TOKEN_1}} "
                "t2={{CANARY_TOKEN_2}} at={{ISSUED_UTC}}\n"
            )
            surfaces = scratch_repo / "surfaces.yaml"
            surfaces.write_text("alpha-one\nbeta-two\n")
            # Copy make-canaries.py into the scratch repo so imports and
            # REPO_DIR resolution work unmodified.
            import shutil
            shutil.copy2(MODULE_PATH, scratch_repo / "make-canaries.py")

            state_file = scratch_repo / ".canary-state.json"
            lock_path = state_file.with_suffix(state_file.suffix + ".lock")
            lock_path.parent.mkdir(parents=True, exist_ok=True)
            holder = open(lock_path, "w")
            try:
                fcntl.flock(holder.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)

                # Registry goes somewhere writable and scratch.
                env = dict(os.environ)
                env["SWANLAKE_REGISTRY"] = str(d_path / "registry.txt")
                result = subprocess.run(
                    [sys.executable, str(scratch_repo / "make-canaries.py")],
                    env=env,
                    capture_output=True,
                    text=True,
                    timeout=10,
                )
                self.assertEqual(
                    result.returncode, 2,
                    f"expected exit 2 when lock is held, got {result.returncode}.\n"
                    f"stdout={result.stdout}\nstderr={result.stderr}"
                )
                self.assertIn(".lock", result.stderr)
                self.assertIn("another make-canaries", result.stderr)
                # State must not exist — the second invocation must have
                # bailed before writing anything.
                self.assertFalse(
                    state_file.exists(),
                    "state file was written despite lock contention — race present",
                )
            finally:
                try:
                    fcntl.flock(holder.fileno(), fcntl.LOCK_UN)
                except Exception:
                    pass
                holder.close()

    def test_sequential_invocations_do_not_corrupt_state(self):
        """After lock released, a fresh invocation proceeds and writes a
        valid JSON state file. Validates the happy path is unaffected by
        the locking instrumentation."""
        with tempfile.TemporaryDirectory() as d:
            d_path = Path(d)
            scratch_repo = d_path / "reference"
            scratch_repo.mkdir()
            (scratch_repo / "beacon-template-v1.md").write_text(
                "id={{SURFACE_ID}} t1={{CANARY_TOKEN_1}} "
                "t2={{CANARY_TOKEN_2}} at={{ISSUED_UTC}}\n"
            )
            (scratch_repo / "surfaces.yaml").write_text("alpha-one\n")
            import shutil
            shutil.copy2(MODULE_PATH, scratch_repo / "make-canaries.py")

            env = dict(os.environ)
            env["SWANLAKE_REGISTRY"] = str(d_path / "registry.txt")

            # First run: cold state.
            r1 = subprocess.run(
                [sys.executable, str(scratch_repo / "make-canaries.py")],
                env=env, capture_output=True, text=True, timeout=10,
            )
            self.assertEqual(r1.returncode, 0, f"first run failed: {r1.stderr}")

            # Second run: warm state, should reuse.
            r2 = subprocess.run(
                [sys.executable, str(scratch_repo / "make-canaries.py")],
                env=env, capture_output=True, text=True, timeout=10,
            )
            self.assertEqual(r2.returncode, 0, f"second run failed: {r2.stderr}")

            state = json.loads((scratch_repo / ".canary-state.json").read_text())
            self.assertIn("alpha-one", state["surfaces"])
            self.assertIn("shaped", state["surfaces"]["alpha-one"])
            self.assertIn("phrase", state["surfaces"]["alpha-one"])


class VersionFlagTest(unittest.TestCase):
    """`--version` is the contract surface that downstream consumers (e.g.
    swanlake's beacon subprocess wrapper) gate on. Must exit 0 and print a
    non-empty version string. Must work without touching ~/.swanlake/, the
    registry, or the state file -- argparse's `version` action short-circuits
    before any filesystem read."""

    def test_version_flag_exits_zero(self):
        result = subprocess.run(
            [sys.executable, str(MODULE_PATH), "--version"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        self.assertEqual(
            result.returncode, 0,
            f"--version exited {result.returncode}; stdout={result.stdout!r}; "
            f"stderr={result.stderr!r}",
        )

    def test_version_flag_prints_non_empty_version(self):
        # argparse's `version` action writes the version line to stdout on
        # Python 3.4+. Combined stdout+stderr handling tolerates accidental
        # routing changes; the assertions here lock the user-visible
        # contract: a recognisable script tag plus a non-empty version
        # string with at least one digit.
        result = subprocess.run(
            [sys.executable, str(MODULE_PATH), "--version"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        printed = (result.stdout + result.stderr).strip()
        self.assertTrue(printed, f"--version printed nothing; got {printed!r}")
        self.assertIn("make-canaries.py", printed)
        version_tail = printed.split("make-canaries.py", 1)[1].strip()
        self.assertTrue(
            version_tail, f"version tail empty after script tag; got {printed!r}",
        )
        self.assertTrue(
            re.search(r"\d", version_tail),
            f"version tail has no digit; got {version_tail!r}",
        )

    def test_module_exposes_version_constant(self):
        """Direct import path must also expose __version__ so callers can
        gate without subprocessing -- belt-and-braces against the CLI flag
        getting renamed in a future refactor."""
        self.assertTrue(hasattr(mc, "__version__"))
        self.assertIsInstance(mc.__version__, str)
        self.assertTrue(mc.__version__.strip())


if __name__ == "__main__":
    unittest.main(verbosity=2)
